//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("InflectorTestModel", "FK_pedidos_usuarios", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EdmxTypist.resources.usuarios), "pedidos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EdmxTypist.resources.pedidos), true)]

#endregion

namespace EdmxTypist.resources
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InflectorTestEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InflectorTestEntities object using the connection string found in the 'InflectorTestEntities' section of the application configuration file.
        /// </summary>
        public InflectorTestEntities() : base("name=InflectorTestEntities", "InflectorTestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InflectorTestEntities object.
        /// </summary>
        public InflectorTestEntities(string connectionString) : base(connectionString, "InflectorTestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InflectorTestEntities object.
        /// </summary>
        public InflectorTestEntities(EntityConnection connection) : base(connection, "InflectorTestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pedidos> pedidos
        {
            get
            {
                if ((_pedidos == null))
                {
                    _pedidos = base.CreateObjectSet<pedidos>("pedidos");
                }
                return _pedidos;
            }
        }
        private ObjectSet<pedidos> _pedidos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pedidos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopedidos(pedidos pedidos)
        {
            base.AddObject("pedidos", pedidos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="user_id">No Metadata Documentation available.</param>
        public ObjectResult<pedidos> get_pedidos(Nullable<global::System.Int32> user_id)
        {
            ObjectParameter user_idParameter;
            if (user_id.HasValue)
            {
                user_idParameter = new ObjectParameter("user_id", user_id);
            }
            else
            {
                user_idParameter = new ObjectParameter("user_id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<pedidos>("get_pedidos", user_idParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="user_id">No Metadata Documentation available.</param>
        public ObjectResult<pedidos> get_pedidos(Nullable<global::System.Int32> user_id, MergeOption mergeOption)
        {
            ObjectParameter user_idParameter;
            if (user_id.HasValue)
            {
                user_idParameter = new ObjectParameter("user_id", user_id);
            }
            else
            {
                user_idParameter = new ObjectParameter("user_id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<pedidos>("get_pedidos", mergeOption, user_idParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InflectorTestModel", Name="pedidos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pedidos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pedidos object.
        /// </summary>
        /// <param name="pedido_id">Initial value of the pedido_id property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static pedidos Createpedidos(global::System.Int32 pedido_id, global::System.Int32 user_id)
        {
            pedidos pedidos = new pedidos();
            pedidos.pedido_id = pedido_id;
            pedidos.user_id = user_id;
            return pedidos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pedido_id
        {
            get
            {
                return _pedido_id;
            }
            set
            {
                if (_pedido_id != value)
                {
                    Onpedido_idChanging(value);
                    ReportPropertyChanging("pedido_id");
                    _pedido_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pedido_id");
                    Onpedido_idChanged();
                }
            }
        }
        private global::System.Int32 _pedido_id;
        partial void Onpedido_idChanging(global::System.Int32 value);
        partial void Onpedido_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> qtd_parcelas
        {
            get
            {
                return _qtd_parcelas;
            }
            set
            {
                Onqtd_parcelasChanging(value);
                ReportPropertyChanging("qtd_parcelas");
                _qtd_parcelas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtd_parcelas");
                Onqtd_parcelasChanged();
            }
        }
        private Nullable<global::System.Int16> _qtd_parcelas;
        partial void Onqtd_parcelasChanging(Nullable<global::System.Int16> value);
        partial void Onqtd_parcelasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> bonus_pontos_boleto
        {
            get
            {
                return _bonus_pontos_boleto;
            }
            set
            {
                Onbonus_pontos_boletoChanging(value);
                ReportPropertyChanging("bonus_pontos_boleto");
                _bonus_pontos_boleto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bonus_pontos_boleto");
                Onbonus_pontos_boletoChanged();
            }
        }
        private Nullable<global::System.Boolean> _bonus_pontos_boleto;
        partial void Onbonus_pontos_boletoChanging(Nullable<global::System.Boolean> value);
        partial void Onbonus_pontos_boletoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> bonus_pontos_boleto_creditado
        {
            get
            {
                return _bonus_pontos_boleto_creditado;
            }
            set
            {
                Onbonus_pontos_boleto_creditadoChanging(value);
                ReportPropertyChanging("bonus_pontos_boleto_creditado");
                _bonus_pontos_boleto_creditado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bonus_pontos_boleto_creditado");
                Onbonus_pontos_boleto_creditadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _bonus_pontos_boleto_creditado;
        partial void Onbonus_pontos_boleto_creditadoChanging(Nullable<global::System.Boolean> value);
        partial void Onbonus_pontos_boleto_creditadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> total
        {
            get
            {
                return _total;
            }
            set
            {
                OntotalChanging(value);
                ReportPropertyChanging("total");
                _total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total");
                OntotalChanged();
            }
        }
        private Nullable<global::System.Int32> _total;
        partial void OntotalChanging(Nullable<global::System.Int32> value);
        partial void OntotalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InflectorTestModel", "FK_pedidos_usuarios", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("InflectorTestModel.FK_pedidos_usuarios", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("InflectorTestModel.FK_pedidos_usuarios", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("InflectorTestModel.FK_pedidos_usuarios", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("InflectorTestModel.FK_pedidos_usuarios", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InflectorTestModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuarios object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="endereco">Initial value of the endereco property.</param>
        public static usuarios Createusuarios(global::System.Int32 user_id, endereco endereco)
        {
            usuarios usuarios = new usuarios();
            usuarios.user_id = user_id;
            usuarios.endereco = StructuralObject.VerifyComplexObjectIsNotNull(endereco, "endereco");
            return usuarios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sexo
        {
            get
            {
                return _sexo;
            }
            set
            {
                OnsexoChanging(value);
                ReportPropertyChanging("sexo");
                _sexo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sexo");
                OnsexoChanged();
            }
        }
        private global::System.String _sexo;
        partial void OnsexoChanging(global::System.String value);
        partial void OnsexoChanged();

        #endregion

        #region Complex Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmComplexPropertyAttribute()]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [XmlElement(IsNullable=true)]
        [SoapElement(IsNullable=true)]
        [DataMemberAttribute()]
        public endereco endereco
        {
            get
            {
                _endereco = GetValidValue(_endereco, "endereco", false, _enderecoInitialized);
                _enderecoInitialized = true;
                return _endereco;
            }
            set
            {
                OnenderecoChanging(value);
                ReportPropertyChanging("endereco");
                _endereco = SetValidValue(_endereco, value, "endereco");
                _enderecoInitialized = true;
                ReportPropertyChanged("endereco");
                OnenderecoChanged();
            }
        }
        private endereco _endereco;
        private bool _enderecoInitialized;
        partial void OnenderecoChanging(endereco value);
        partial void OnenderecoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InflectorTestModel", "FK_pedidos_usuarios", "pedidos")]
        public EntityCollection<pedidos> pedidos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<pedidos>("InflectorTestModel.FK_pedidos_usuarios", "pedidos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<pedidos>("InflectorTestModel.FK_pedidos_usuarios", "pedidos", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="InflectorTestModel", Name="endereco")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class endereco : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cep
        {
            get
            {
                return _cep;
            }
            set
            {
                OncepChanging(value);
                ReportPropertyChanging("cep");
                _cep = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cep");
                OncepChanged();
            }
        }
        private global::System.String _cep;
        partial void OncepChanging(global::System.String value);
        partial void OncepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cidade
        {
            get
            {
                return _cidade;
            }
            set
            {
                OncidadeChanging(value);
                ReportPropertyChanging("cidade");
                _cidade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cidade");
                OncidadeChanged();
            }
        }
        private global::System.String _cidade;
        partial void OncidadeChanging(global::System.String value);
        partial void OncidadeChanged();

        #endregion

    }

    #endregion

    
}
