//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MinModel", "usuariosBlogComentariosUsers", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EdmxTool.Tests.resources.usuarios), "BlogComentarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EdmxTool.Tests.resources.BlogComentariosUsers), true)]

#endregion

namespace EdmxTool.Tests.resources
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class camiseteriaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new camiseteriaEntities object using the connection string found in the 'camiseteriaEntities' section of the application configuration file.
        /// </summary>
        public camiseteriaEntities() : base("name=camiseteriaEntities", "camiseteriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new camiseteriaEntities object.
        /// </summary>
        public camiseteriaEntities(string connectionString) : base(connectionString, "camiseteriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new camiseteriaEntities object.
        /// </summary>
        public camiseteriaEntities(EntityConnection connection) : base(connection, "camiseteriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlogComentariosUsers> blog_comentarios_users
        {
            get
            {
                if ((_blog_comentarios_users == null))
                {
                    _blog_comentarios_users = base.CreateObjectSet<BlogComentariosUsers>("blog_comentarios_users");
                }
                return _blog_comentarios_users;
            }
        }
        private ObjectSet<BlogComentariosUsers> _blog_comentarios_users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the blog_comentarios_users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToblog_comentarios_users(BlogComentariosUsers blogComentariosUsers)
        {
            base.AddObject("blog_comentarios_users", blogComentariosUsers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MinModel", Name="BlogComentariosUsers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogComentariosUsers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlogComentariosUsers object.
        /// </summary>
        /// <param name="blogComentarioId">Initial value of the BlogComentarioId property.</param>
        /// <param name="blogPostId">Initial value of the BlogPostId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="comentario">Initial value of the Comentario property.</param>
        /// <param name="aprovado">Initial value of the Aprovado property.</param>
        /// <param name="dataIns">Initial value of the DataIns property.</param>
        public static BlogComentariosUsers CreateBlogComentariosUsers(global::System.Int32 blogComentarioId, global::System.Int32 blogPostId, global::System.Int32 userId, global::System.String comentario, global::System.Byte aprovado, global::System.DateTime dataIns)
        {
            BlogComentariosUsers blogComentariosUsers = new BlogComentariosUsers();
            blogComentariosUsers.BlogComentarioId = blogComentarioId;
            blogComentariosUsers.BlogPostId = blogPostId;
            blogComentariosUsers.UserId = userId;
            blogComentariosUsers.Comentario = comentario;
            blogComentariosUsers.Aprovado = aprovado;
            blogComentariosUsers.DataIns = dataIns;
            return blogComentariosUsers;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogComentarioId
        {
            get
            {
                return _BlogComentarioId;
            }
            set
            {
                if (_BlogComentarioId != value)
                {
                    OnBlogComentarioIdChanging(value);
                    ReportPropertyChanging("BlogComentarioId");
                    _BlogComentarioId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BlogComentarioId");
                    OnBlogComentarioIdChanged();
                }
            }
        }
        private global::System.Int32 _BlogComentarioId;
        partial void OnBlogComentarioIdChanging(global::System.Int32 value);
        partial void OnBlogComentarioIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogPostId
        {
            get
            {
                return _BlogPostId;
            }
            set
            {
                if (_BlogPostId != value)
                {
                    OnBlogPostIdChanging(value);
                    ReportPropertyChanging("BlogPostId");
                    _BlogPostId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BlogPostId");
                    OnBlogPostIdChanged();
                }
            }
        }
        private global::System.Int32 _BlogPostId;
        partial void OnBlogPostIdChanging(global::System.Int32 value);
        partial void OnBlogPostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comentario
        {
            get
            {
                return _Comentario;
            }
            set
            {
                OnComentarioChanging(value);
                ReportPropertyChanging("Comentario");
                _Comentario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comentario");
                OnComentarioChanged();
            }
        }
        private global::System.String _Comentario;
        partial void OnComentarioChanging(global::System.String value);
        partial void OnComentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Aprovado
        {
            get
            {
                return _Aprovado;
            }
            set
            {
                OnAprovadoChanging(value);
                ReportPropertyChanging("Aprovado");
                _Aprovado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Aprovado");
                OnAprovadoChanged();
            }
        }
        private global::System.Byte _Aprovado;
        partial void OnAprovadoChanging(global::System.Byte value);
        partial void OnAprovadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataIns
        {
            get
            {
                return _DataIns;
            }
            set
            {
                OnDataInsChanging(value);
                ReportPropertyChanging("DataIns");
                _DataIns = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataIns");
                OnDataInsChanged();
            }
        }
        private global::System.DateTime _DataIns;
        partial void OnDataInsChanging(global::System.DateTime value);
        partial void OnDataInsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PaiBlogComentarioId
        {
            get
            {
                return _PaiBlogComentarioId;
            }
            set
            {
                OnPaiBlogComentarioIdChanging(value);
                ReportPropertyChanging("PaiBlogComentarioId");
                _PaiBlogComentarioId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaiBlogComentarioId");
                OnPaiBlogComentarioIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PaiBlogComentarioId;
        partial void OnPaiBlogComentarioIdChanging(Nullable<global::System.Int32> value);
        partial void OnPaiBlogComentarioIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PaiBlogPostId
        {
            get
            {
                return _PaiBlogPostId;
            }
            set
            {
                OnPaiBlogPostIdChanging(value);
                ReportPropertyChanging("PaiBlogPostId");
                _PaiBlogPostId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaiBlogPostId");
                OnPaiBlogPostIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PaiBlogPostId;
        partial void OnPaiBlogPostIdChanging(Nullable<global::System.Int32> value);
        partial void OnPaiBlogPostIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MinModel", "usuariosBlogComentariosUsers", "Usuario")]
        public usuarios UsuarioXXX
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("MinModel.usuariosBlogComentariosUsers", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("MinModel.usuariosBlogComentariosUsers", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> UsuarioXXXReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("MinModel.usuariosBlogComentariosUsers", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("MinModel.usuariosBlogComentariosUsers", "Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MinModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuarios object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="data_ins">Initial value of the data_ins property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="recebe_news">Initial value of the recebe_news property.</param>
        /// <param name="pais_id">Initial value of the pais_id property.</param>
        /// <param name="saldo_pontos">Initial value of the saldo_pontos property.</param>
        /// <param name="foto_status">Initial value of the foto_status property.</param>
        /// <param name="grau_premio">Initial value of the grau_premio property.</param>
        /// <param name="convidado">Initial value of the convidado property.</param>
        /// <param name="qtd_visualizacoes">Initial value of the qtd_visualizacoes property.</param>
        /// <param name="clubevip">Initial value of the clubevip property.</param>
        /// <param name="pode_blogar_novidades">Initial value of the pode_blogar_novidades property.</param>
        /// <param name="fretegratis">Initial value of the fretegratis property.</param>
        /// <param name="fundador">Initial value of the fundador property.</param>
        /// <param name="ativo">Initial value of the ativo property.</param>
        /// <param name="fake">Initial value of the fake property.</param>
        /// <param name="mes_ins">Initial value of the mes_ins property.</param>
        /// <param name="online">Initial value of the online property.</param>
        /// <param name="recebe_promocoes">Initial value of the recebe_promocoes property.</param>
        /// <param name="email_bouncing">Initial value of the email_bouncing property.</param>
        /// <param name="senha2">Initial value of the senha2 property.</param>
        /// <param name="confiavel">Initial value of the confiavel property.</param>
        public static usuarios Createusuarios(global::System.Int32 user_id, global::System.String username, global::System.DateTime data_ins, global::System.String nome, global::System.String email, global::System.Byte recebe_news, global::System.Int32 pais_id, global::System.Decimal saldo_pontos, global::System.String foto_status, global::System.Byte grau_premio, global::System.Byte convidado, global::System.Int32 qtd_visualizacoes, global::System.Byte clubevip, global::System.Byte pode_blogar_novidades, global::System.Byte fretegratis, global::System.Byte fundador, global::System.Byte ativo, global::System.Byte fake, global::System.DateTime mes_ins, global::System.Byte online, global::System.Byte recebe_promocoes, global::System.Byte email_bouncing, global::System.String senha2, global::System.Byte confiavel)
        {
            usuarios usuarios = new usuarios();
            usuarios.user_id = user_id;
            usuarios.username = username;
            usuarios.data_ins = data_ins;
            usuarios.nome = nome;
            usuarios.email = email;
            usuarios.recebe_news = recebe_news;
            usuarios.pais_id = pais_id;
            usuarios.saldo_pontos = saldo_pontos;
            usuarios.foto_status = foto_status;
            usuarios.grau_premio = grau_premio;
            usuarios.convidado = convidado;
            usuarios.qtd_visualizacoes = qtd_visualizacoes;
            usuarios.clubevip = clubevip;
            usuarios.pode_blogar_novidades = pode_blogar_novidades;
            usuarios.fretegratis = fretegratis;
            usuarios.fundador = fundador;
            usuarios.ativo = ativo;
            usuarios.fake = fake;
            usuarios.mes_ins = mes_ins;
            usuarios.online = online;
            usuarios.recebe_promocoes = recebe_promocoes;
            usuarios.email_bouncing = email_bouncing;
            usuarios.senha2 = senha2;
            usuarios.confiavel = confiavel;
            return usuarios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data_ins
        {
            get
            {
                return _data_ins;
            }
            set
            {
                Ondata_insChanging(value);
                ReportPropertyChanging("data_ins");
                _data_ins = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_ins");
                Ondata_insChanged();
            }
        }
        private global::System.DateTime _data_ins;
        partial void Ondata_insChanging(global::System.DateTime value);
        partial void Ondata_insChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> mostrar_perfil
        {
            get
            {
                return _mostrar_perfil;
            }
            set
            {
                Onmostrar_perfilChanging(value);
                ReportPropertyChanging("mostrar_perfil");
                _mostrar_perfil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mostrar_perfil");
                Onmostrar_perfilChanged();
            }
        }
        private Nullable<global::System.Byte> _mostrar_perfil;
        partial void Onmostrar_perfilChanging(Nullable<global::System.Byte> value);
        partial void Onmostrar_perfilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte recebe_news
        {
            get
            {
                return _recebe_news;
            }
            set
            {
                Onrecebe_newsChanging(value);
                ReportPropertyChanging("recebe_news");
                _recebe_news = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recebe_news");
                Onrecebe_newsChanged();
            }
        }
        private global::System.Byte _recebe_news;
        partial void Onrecebe_newsChanging(global::System.Byte value);
        partial void Onrecebe_newsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hometown
        {
            get
            {
                return _hometown;
            }
            set
            {
                OnhometownChanging(value);
                ReportPropertyChanging("hometown");
                _hometown = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hometown");
                OnhometownChanged();
            }
        }
        private global::System.String _hometown;
        partial void OnhometownChanging(global::System.String value);
        partial void OnhometownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pais_id
        {
            get
            {
                return _pais_id;
            }
            set
            {
                Onpais_idChanging(value);
                ReportPropertyChanging("pais_id");
                _pais_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pais_id");
                Onpais_idChanged();
            }
        }
        private global::System.Int32 _pais_id;
        partial void Onpais_idChanging(global::System.Int32 value);
        partial void Onpais_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal saldo_pontos
        {
            get
            {
                return _saldo_pontos;
            }
            set
            {
                Onsaldo_pontosChanging(value);
                ReportPropertyChanging("saldo_pontos");
                _saldo_pontos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("saldo_pontos");
                Onsaldo_pontosChanged();
            }
        }
        private global::System.Decimal _saldo_pontos;
        partial void Onsaldo_pontosChanging(global::System.Decimal value);
        partial void Onsaldo_pontosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String foto_status
        {
            get
            {
                return _foto_status;
            }
            set
            {
                Onfoto_statusChanging(value);
                ReportPropertyChanging("foto_status");
                _foto_status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("foto_status");
                Onfoto_statusChanged();
            }
        }
        private global::System.String _foto_status;
        partial void Onfoto_statusChanging(global::System.String value);
        partial void Onfoto_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String yahoo
        {
            get
            {
                return _yahoo;
            }
            set
            {
                OnyahooChanging(value);
                ReportPropertyChanging("yahoo");
                _yahoo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("yahoo");
                OnyahooChanged();
            }
        }
        private global::System.String _yahoo;
        partial void OnyahooChanging(global::System.String value);
        partial void OnyahooChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icq
        {
            get
            {
                return _icq;
            }
            set
            {
                OnicqChanging(value);
                ReportPropertyChanging("icq");
                _icq = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icq");
                OnicqChanged();
            }
        }
        private global::System.String _icq;
        partial void OnicqChanging(global::System.String value);
        partial void OnicqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String messenger
        {
            get
            {
                return _messenger;
            }
            set
            {
                OnmessengerChanging(value);
                ReportPropertyChanging("messenger");
                _messenger = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("messenger");
                OnmessengerChanged();
            }
        }
        private global::System.String _messenger;
        partial void OnmessengerChanging(global::System.String value);
        partial void OnmessengerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sexo
        {
            get
            {
                return _sexo;
            }
            set
            {
                OnsexoChanging(value);
                ReportPropertyChanging("sexo");
                _sexo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sexo");
                OnsexoChanged();
            }
        }
        private global::System.String _sexo;
        partial void OnsexoChanging(global::System.String value);
        partial void OnsexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_nasc
        {
            get
            {
                return _data_nasc;
            }
            set
            {
                Ondata_nascChanging(value);
                ReportPropertyChanging("data_nasc");
                _data_nasc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_nasc");
                Ondata_nascChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_nasc;
        partial void Ondata_nascChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_nascChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aol
        {
            get
            {
                return _aol;
            }
            set
            {
                OnaolChanging(value);
                ReportPropertyChanging("aol");
                _aol = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aol");
                OnaolChanged();
            }
        }
        private global::System.String _aol;
        partial void OnaolChanging(global::System.String value);
        partial void OnaolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ocupacao
        {
            get
            {
                return _ocupacao;
            }
            set
            {
                OnocupacaoChanging(value);
                ReportPropertyChanging("ocupacao");
                _ocupacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ocupacao");
                OnocupacaoChanged();
            }
        }
        private global::System.String _ocupacao;
        partial void OnocupacaoChanging(global::System.String value);
        partial void OnocupacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone
        {
            get
            {
                return _telefone;
            }
            set
            {
                OntelefoneChanging(value);
                ReportPropertyChanging("telefone");
                _telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefone");
                OntelefoneChanged();
            }
        }
        private global::System.String _telefone;
        partial void OntelefoneChanging(global::System.String value);
        partial void OntelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String favorecido
        {
            get
            {
                return _favorecido;
            }
            set
            {
                OnfavorecidoChanging(value);
                ReportPropertyChanging("favorecido");
                _favorecido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("favorecido");
                OnfavorecidoChanged();
            }
        }
        private global::System.String _favorecido;
        partial void OnfavorecidoChanging(global::System.String value);
        partial void OnfavorecidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String conta
        {
            get
            {
                return _conta;
            }
            set
            {
                OncontaChanging(value);
                ReportPropertyChanging("conta");
                _conta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("conta");
                OncontaChanged();
            }
        }
        private global::System.String _conta;
        partial void OncontaChanging(global::System.String value);
        partial void OncontaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agencia
        {
            get
            {
                return _agencia;
            }
            set
            {
                OnagenciaChanging(value);
                ReportPropertyChanging("agencia");
                _agencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agencia");
                OnagenciaChanged();
            }
        }
        private global::System.String _agencia;
        partial void OnagenciaChanging(global::System.String value);
        partial void OnagenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> banco
        {
            get
            {
                return _banco;
            }
            set
            {
                OnbancoChanging(value);
                ReportPropertyChanging("banco");
                _banco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("banco");
                OnbancoChanged();
            }
        }
        private Nullable<global::System.Int16> _banco;
        partial void OnbancoChanging(Nullable<global::System.Int16> value);
        partial void OnbancoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> aceitou_receber_news
        {
            get
            {
                return _aceitou_receber_news;
            }
            set
            {
                Onaceitou_receber_newsChanging(value);
                ReportPropertyChanging("aceitou_receber_news");
                _aceitou_receber_news = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("aceitou_receber_news");
                Onaceitou_receber_newsChanged();
            }
        }
        private Nullable<global::System.Byte> _aceitou_receber_news;
        partial void Onaceitou_receber_newsChanging(Nullable<global::System.Byte> value);
        partial void Onaceitou_receber_newsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte grau_premio
        {
            get
            {
                return _grau_premio;
            }
            set
            {
                Ongrau_premioChanging(value);
                ReportPropertyChanging("grau_premio");
                _grau_premio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("grau_premio");
                Ongrau_premioChanged();
            }
        }
        private global::System.Byte _grau_premio;
        partial void Ongrau_premioChanging(global::System.Byte value);
        partial void Ongrau_premioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte convidado
        {
            get
            {
                return _convidado;
            }
            set
            {
                OnconvidadoChanging(value);
                ReportPropertyChanging("convidado");
                _convidado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("convidado");
                OnconvidadoChanged();
            }
        }
        private global::System.Byte _convidado;
        partial void OnconvidadoChanging(global::System.Byte value);
        partial void OnconvidadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qtd_visualizacoes
        {
            get
            {
                return _qtd_visualizacoes;
            }
            set
            {
                Onqtd_visualizacoesChanging(value);
                ReportPropertyChanging("qtd_visualizacoes");
                _qtd_visualizacoes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtd_visualizacoes");
                Onqtd_visualizacoesChanged();
            }
        }
        private global::System.Int32 _qtd_visualizacoes;
        partial void Onqtd_visualizacoesChanging(global::System.Int32 value);
        partial void Onqtd_visualizacoesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> veiculo_id
        {
            get
            {
                return _veiculo_id;
            }
            set
            {
                Onveiculo_idChanging(value);
                ReportPropertyChanging("veiculo_id");
                _veiculo_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("veiculo_id");
                Onveiculo_idChanged();
            }
        }
        private Nullable<global::System.Int32> _veiculo_id;
        partial void Onveiculo_idChanging(Nullable<global::System.Int32> value);
        partial void Onveiculo_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> indicador_user_id
        {
            get
            {
                return _indicador_user_id;
            }
            set
            {
                Onindicador_user_idChanging(value);
                ReportPropertyChanging("indicador_user_id");
                _indicador_user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("indicador_user_id");
                Onindicador_user_idChanged();
            }
        }
        private Nullable<global::System.Int32> _indicador_user_id;
        partial void Onindicador_user_idChanging(Nullable<global::System.Int32> value);
        partial void Onindicador_user_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte clubevip
        {
            get
            {
                return _clubevip;
            }
            set
            {
                OnclubevipChanging(value);
                ReportPropertyChanging("clubevip");
                _clubevip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("clubevip");
                OnclubevipChanged();
            }
        }
        private global::System.Byte _clubevip;
        partial void OnclubevipChanging(global::System.Byte value);
        partial void OnclubevipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte pode_blogar_novidades
        {
            get
            {
                return _pode_blogar_novidades;
            }
            set
            {
                Onpode_blogar_novidadesChanging(value);
                ReportPropertyChanging("pode_blogar_novidades");
                _pode_blogar_novidades = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pode_blogar_novidades");
                Onpode_blogar_novidadesChanged();
            }
        }
        private global::System.Byte _pode_blogar_novidades;
        partial void Onpode_blogar_novidadesChanging(global::System.Byte value);
        partial void Onpode_blogar_novidadesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte fretegratis
        {
            get
            {
                return _fretegratis;
            }
            set
            {
                OnfretegratisChanging(value);
                ReportPropertyChanging("fretegratis");
                _fretegratis = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fretegratis");
                OnfretegratisChanged();
            }
        }
        private global::System.Byte _fretegratis;
        partial void OnfretegratisChanging(global::System.Byte value);
        partial void OnfretegratisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String googletalk
        {
            get
            {
                return _googletalk;
            }
            set
            {
                OngoogletalkChanging(value);
                ReportPropertyChanging("googletalk");
                _googletalk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("googletalk");
                OngoogletalkChanged();
            }
        }
        private global::System.String _googletalk;
        partial void OngoogletalkChanging(global::System.String value);
        partial void OngoogletalkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte fundador
        {
            get
            {
                return _fundador;
            }
            set
            {
                OnfundadorChanging(value);
                ReportPropertyChanging("fundador");
                _fundador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fundador");
                OnfundadorChanged();
            }
        }
        private global::System.Byte _fundador;
        partial void OnfundadorChanging(global::System.Byte value);
        partial void OnfundadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parceiro_id
        {
            get
            {
                return _parceiro_id;
            }
            set
            {
                Onparceiro_idChanging(value);
                ReportPropertyChanging("parceiro_id");
                _parceiro_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parceiro_id");
                Onparceiro_idChanged();
            }
        }
        private Nullable<global::System.Int32> _parceiro_id;
        partial void Onparceiro_idChanging(Nullable<global::System.Int32> value);
        partial void Onparceiro_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte ativo
        {
            get
            {
                return _ativo;
            }
            set
            {
                OnativoChanging(value);
                ReportPropertyChanging("ativo");
                _ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ativo");
                OnativoChanged();
            }
        }
        private global::System.Byte _ativo;
        partial void OnativoChanging(global::System.Byte value);
        partial void OnativoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte fake
        {
            get
            {
                return _fake;
            }
            set
            {
                OnfakeChanging(value);
                ReportPropertyChanging("fake");
                _fake = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fake");
                OnfakeChanged();
            }
        }
        private global::System.Byte _fake;
        partial void OnfakeChanging(global::System.Byte value);
        partial void OnfakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> recebe_aviso_scrap
        {
            get
            {
                return _recebe_aviso_scrap;
            }
            set
            {
                Onrecebe_aviso_scrapChanging(value);
                ReportPropertyChanging("recebe_aviso_scrap");
                _recebe_aviso_scrap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recebe_aviso_scrap");
                Onrecebe_aviso_scrapChanged();
            }
        }
        private Nullable<global::System.Byte> _recebe_aviso_scrap;
        partial void Onrecebe_aviso_scrapChanging(Nullable<global::System.Byte> value);
        partial void Onrecebe_aviso_scrapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> recebe_aviso_blog
        {
            get
            {
                return _recebe_aviso_blog;
            }
            set
            {
                Onrecebe_aviso_blogChanging(value);
                ReportPropertyChanging("recebe_aviso_blog");
                _recebe_aviso_blog = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recebe_aviso_blog");
                Onrecebe_aviso_blogChanged();
            }
        }
        private Nullable<global::System.Byte> _recebe_aviso_blog;
        partial void Onrecebe_aviso_blogChanging(Nullable<global::System.Byte> value);
        partial void Onrecebe_aviso_blogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> recebe_aviso_comentario
        {
            get
            {
                return _recebe_aviso_comentario;
            }
            set
            {
                Onrecebe_aviso_comentarioChanging(value);
                ReportPropertyChanging("recebe_aviso_comentario");
                _recebe_aviso_comentario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recebe_aviso_comentario");
                Onrecebe_aviso_comentarioChanged();
            }
        }
        private Nullable<global::System.Byte> _recebe_aviso_comentario;
        partial void Onrecebe_aviso_comentarioChanging(Nullable<global::System.Byte> value);
        partial void Onrecebe_aviso_comentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime mes_ins
        {
            get
            {
                return _mes_ins;
            }
            set
            {
                Onmes_insChanging(value);
                ReportPropertyChanging("mes_ins");
                _mes_ins = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mes_ins");
                Onmes_insChanged();
            }
        }
        private global::System.DateTime _mes_ins;
        partial void Onmes_insChanging(global::System.DateTime value);
        partial void Onmes_insChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> email_validado_nivel1
        {
            get
            {
                return _email_validado_nivel1;
            }
            set
            {
                Onemail_validado_nivel1Changing(value);
                ReportPropertyChanging("email_validado_nivel1");
                _email_validado_nivel1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("email_validado_nivel1");
                Onemail_validado_nivel1Changed();
            }
        }
        private Nullable<global::System.Byte> _email_validado_nivel1;
        partial void Onemail_validado_nivel1Changing(Nullable<global::System.Byte> value);
        partial void Onemail_validado_nivel1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> email_validado_nivel2
        {
            get
            {
                return _email_validado_nivel2;
            }
            set
            {
                Onemail_validado_nivel2Changing(value);
                ReportPropertyChanging("email_validado_nivel2");
                _email_validado_nivel2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("email_validado_nivel2");
                Onemail_validado_nivel2Changed();
            }
        }
        private Nullable<global::System.Byte> _email_validado_nivel2;
        partial void Onemail_validado_nivel2Changing(Nullable<global::System.Byte> value);
        partial void Onemail_validado_nivel2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip
        {
            get
            {
                return _ip;
            }
            set
            {
                OnipChanging(value);
                ReportPropertyChanging("ip");
                _ip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip");
                OnipChanged();
            }
        }
        private global::System.String _ip;
        partial void OnipChanging(global::System.String value);
        partial void OnipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ranking
        {
            get
            {
                return _ranking;
            }
            set
            {
                OnrankingChanging(value);
                ReportPropertyChanging("ranking");
                _ranking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ranking");
                OnrankingChanged();
            }
        }
        private Nullable<global::System.Double> _ranking;
        partial void OnrankingChanging(Nullable<global::System.Double> value);
        partial void OnrankingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte online
        {
            get
            {
                return _online;
            }
            set
            {
                OnonlineChanging(value);
                ReportPropertyChanging("online");
                _online = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("online");
                OnonlineChanged();
            }
        }
        private global::System.Byte _online;
        partial void OnonlineChanging(global::System.Byte value);
        partial void OnonlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opensocial_personid
        {
            get
            {
                return _opensocial_personid;
            }
            set
            {
                Onopensocial_personidChanging(value);
                ReportPropertyChanging("opensocial_personid");
                _opensocial_personid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("opensocial_personid");
                Onopensocial_personidChanged();
            }
        }
        private global::System.String _opensocial_personid;
        partial void Onopensocial_personidChanging(global::System.String value);
        partial void Onopensocial_personidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opensocial_container
        {
            get
            {
                return _opensocial_container;
            }
            set
            {
                Onopensocial_containerChanging(value);
                ReportPropertyChanging("opensocial_container");
                _opensocial_container = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("opensocial_container");
                Onopensocial_containerChanged();
            }
        }
        private global::System.String _opensocial_container;
        partial void Onopensocial_containerChanging(global::System.String value);
        partial void Onopensocial_containerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte recebe_promocoes
        {
            get
            {
                return _recebe_promocoes;
            }
            set
            {
                Onrecebe_promocoesChanging(value);
                ReportPropertyChanging("recebe_promocoes");
                _recebe_promocoes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recebe_promocoes");
                Onrecebe_promocoesChanged();
            }
        }
        private global::System.Byte _recebe_promocoes;
        partial void Onrecebe_promocoesChanging(global::System.Byte value);
        partial void Onrecebe_promocoesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String referrer
        {
            get
            {
                return _referrer;
            }
            set
            {
                OnreferrerChanging(value);
                ReportPropertyChanging("referrer");
                _referrer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("referrer");
                OnreferrerChanged();
            }
        }
        private global::System.String _referrer;
        partial void OnreferrerChanging(global::System.String value);
        partial void OnreferrerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte email_bouncing
        {
            get
            {
                return _email_bouncing;
            }
            set
            {
                Onemail_bouncingChanging(value);
                ReportPropertyChanging("email_bouncing");
                _email_bouncing = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("email_bouncing");
                Onemail_bouncingChanged();
            }
        }
        private global::System.Byte _email_bouncing;
        partial void Onemail_bouncingChanging(global::System.Byte value);
        partial void Onemail_bouncingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String senha2
        {
            get
            {
                return _senha2;
            }
            set
            {
                Onsenha2Changing(value);
                ReportPropertyChanging("senha2");
                _senha2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("senha2");
                Onsenha2Changed();
            }
        }
        private global::System.String _senha2;
        partial void Onsenha2Changing(global::System.String value);
        partial void Onsenha2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String checkGuid
        {
            get
            {
                return _checkGuid;
            }
            set
            {
                OncheckGuidChanging(value);
                ReportPropertyChanging("checkGuid");
                _checkGuid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("checkGuid");
                OncheckGuidChanged();
            }
        }
        private global::System.String _checkGuid;
        partial void OncheckGuidChanging(global::System.String value);
        partial void OncheckGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String twitter
        {
            get
            {
                return _twitter;
            }
            set
            {
                OntwitterChanging(value);
                ReportPropertyChanging("twitter");
                _twitter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("twitter");
                OntwitterChanged();
            }
        }
        private global::System.String _twitter;
        partial void OntwitterChanging(global::System.String value);
        partial void OntwitterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> facebook_uid
        {
            get
            {
                return _facebook_uid;
            }
            set
            {
                Onfacebook_uidChanging(value);
                ReportPropertyChanging("facebook_uid");
                _facebook_uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("facebook_uid");
                Onfacebook_uidChanged();
            }
        }
        private Nullable<global::System.Int64> _facebook_uid;
        partial void Onfacebook_uidChanging(Nullable<global::System.Int64> value);
        partial void Onfacebook_uidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String documento
        {
            get
            {
                return _documento;
            }
            set
            {
                OndocumentoChanging(value);
                ReportPropertyChanging("documento");
                _documento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("documento");
                OndocumentoChanged();
            }
        }
        private global::System.String _documento;
        partial void OndocumentoChanging(global::System.String value);
        partial void OndocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String twitter_oauth_token
        {
            get
            {
                return _twitter_oauth_token;
            }
            set
            {
                Ontwitter_oauth_tokenChanging(value);
                ReportPropertyChanging("twitter_oauth_token");
                _twitter_oauth_token = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("twitter_oauth_token");
                Ontwitter_oauth_tokenChanged();
            }
        }
        private global::System.String _twitter_oauth_token;
        partial void Ontwitter_oauth_tokenChanging(global::System.String value);
        partial void Ontwitter_oauth_tokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String twitter_oauth_token_secret
        {
            get
            {
                return _twitter_oauth_token_secret;
            }
            set
            {
                Ontwitter_oauth_token_secretChanging(value);
                ReportPropertyChanging("twitter_oauth_token_secret");
                _twitter_oauth_token_secret = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("twitter_oauth_token_secret");
                Ontwitter_oauth_token_secretChanged();
            }
        }
        private global::System.String _twitter_oauth_token_secret;
        partial void Ontwitter_oauth_token_secretChanging(global::System.String value);
        partial void Ontwitter_oauth_token_secretChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String twitter_oauth_screen_name
        {
            get
            {
                return _twitter_oauth_screen_name;
            }
            set
            {
                Ontwitter_oauth_screen_nameChanging(value);
                ReportPropertyChanging("twitter_oauth_screen_name");
                _twitter_oauth_screen_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("twitter_oauth_screen_name");
                Ontwitter_oauth_screen_nameChanged();
            }
        }
        private global::System.String _twitter_oauth_screen_name;
        partial void Ontwitter_oauth_screen_nameChanging(global::System.String value);
        partial void Ontwitter_oauth_screen_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> twitter_oauth_user_id
        {
            get
            {
                return _twitter_oauth_user_id;
            }
            set
            {
                Ontwitter_oauth_user_idChanging(value);
                ReportPropertyChanging("twitter_oauth_user_id");
                _twitter_oauth_user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("twitter_oauth_user_id");
                Ontwitter_oauth_user_idChanged();
            }
        }
        private Nullable<global::System.Int32> _twitter_oauth_user_id;
        partial void Ontwitter_oauth_user_idChanging(Nullable<global::System.Int32> value);
        partial void Ontwitter_oauth_user_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> convidado_facebook
        {
            get
            {
                return _convidado_facebook;
            }
            set
            {
                Onconvidado_facebookChanging(value);
                ReportPropertyChanging("convidado_facebook");
                _convidado_facebook = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("convidado_facebook");
                Onconvidado_facebookChanged();
            }
        }
        private Nullable<global::System.Byte> _convidado_facebook;
        partial void Onconvidado_facebookChanging(Nullable<global::System.Byte> value);
        partial void Onconvidado_facebookChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> canal_veiculo_id
        {
            get
            {
                return _canal_veiculo_id;
            }
            set
            {
                Oncanal_veiculo_idChanging(value);
                ReportPropertyChanging("canal_veiculo_id");
                _canal_veiculo_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("canal_veiculo_id");
                Oncanal_veiculo_idChanged();
            }
        }
        private Nullable<global::System.Int32> _canal_veiculo_id;
        partial void Oncanal_veiculo_idChanging(Nullable<global::System.Int32> value);
        partial void Oncanal_veiculo_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> designs_aprovados
        {
            get
            {
                return _designs_aprovados;
            }
            set
            {
                Ondesigns_aprovadosChanging(value);
                ReportPropertyChanging("designs_aprovados");
                _designs_aprovados = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("designs_aprovados");
                Ondesigns_aprovadosChanged();
            }
        }
        private Nullable<global::System.Int16> _designs_aprovados;
        partial void Ondesigns_aprovadosChanging(Nullable<global::System.Int16> value);
        partial void Ondesigns_aprovadosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> staff
        {
            get
            {
                return _staff;
            }
            set
            {
                OnstaffChanging(value);
                ReportPropertyChanging("staff");
                _staff = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("staff");
                OnstaffChanged();
            }
        }
        private Nullable<global::System.Byte> _staff;
        partial void OnstaffChanging(Nullable<global::System.Byte> value);
        partial void OnstaffChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> suspeita_fraude
        {
            get
            {
                return _suspeita_fraude;
            }
            set
            {
                Onsuspeita_fraudeChanging(value);
                ReportPropertyChanging("suspeita_fraude");
                _suspeita_fraude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("suspeita_fraude");
                Onsuspeita_fraudeChanged();
            }
        }
        private Nullable<global::System.Byte> _suspeita_fraude;
        partial void Onsuspeita_fraudeChanging(Nullable<global::System.Byte> value);
        partial void Onsuspeita_fraudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> fraudulento
        {
            get
            {
                return _fraudulento;
            }
            set
            {
                OnfraudulentoChanging(value);
                ReportPropertyChanging("fraudulento");
                _fraudulento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fraudulento");
                OnfraudulentoChanged();
            }
        }
        private Nullable<global::System.Byte> _fraudulento;
        partial void OnfraudulentoChanging(Nullable<global::System.Byte> value);
        partial void OnfraudulentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte confiavel
        {
            get
            {
                return _confiavel;
            }
            set
            {
                OnconfiavelChanging(value);
                ReportPropertyChanging("confiavel");
                _confiavel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("confiavel");
                OnconfiavelChanged();
            }
        }
        private global::System.Byte _confiavel;
        partial void OnconfiavelChanging(global::System.Byte value);
        partial void OnconfiavelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reset_senha_guid
        {
            get
            {
                return _reset_senha_guid;
            }
            set
            {
                Onreset_senha_guidChanging(value);
                ReportPropertyChanging("reset_senha_guid");
                _reset_senha_guid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reset_senha_guid");
                Onreset_senha_guidChanged();
            }
        }
        private global::System.String _reset_senha_guid;
        partial void Onreset_senha_guidChanging(global::System.String value);
        partial void Onreset_senha_guidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> validade_reset_senha
        {
            get
            {
                return _validade_reset_senha;
            }
            set
            {
                Onvalidade_reset_senhaChanging(value);
                ReportPropertyChanging("validade_reset_senha");
                _validade_reset_senha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("validade_reset_senha");
                Onvalidade_reset_senhaChanged();
            }
        }
        private Nullable<global::System.DateTime> _validade_reset_senha;
        partial void Onvalidade_reset_senhaChanging(Nullable<global::System.DateTime> value);
        partial void Onvalidade_reset_senhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> recebe_votou
        {
            get
            {
                return _recebe_votou;
            }
            set
            {
                Onrecebe_votouChanging(value);
                ReportPropertyChanging("recebe_votou");
                _recebe_votou = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recebe_votou");
                Onrecebe_votouChanged();
            }
        }
        private Nullable<global::System.Byte> _recebe_votou;
        partial void Onrecebe_votouChanging(Nullable<global::System.Byte> value);
        partial void Onrecebe_votouChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_ultima_visita_bb
        {
            get
            {
                return _data_ultima_visita_bb;
            }
            set
            {
                Ondata_ultima_visita_bbChanging(value);
                ReportPropertyChanging("data_ultima_visita_bb");
                _data_ultima_visita_bb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_ultima_visita_bb");
                Ondata_ultima_visita_bbChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_ultima_visita_bb;
        partial void Ondata_ultima_visita_bbChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_ultima_visita_bbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_ultima_visita_dbb
        {
            get
            {
                return _data_ultima_visita_dbb;
            }
            set
            {
                Ondata_ultima_visita_dbbChanging(value);
                ReportPropertyChanging("data_ultima_visita_dbb");
                _data_ultima_visita_dbb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_ultima_visita_dbb");
                Ondata_ultima_visita_dbbChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_ultima_visita_dbb;
        partial void Ondata_ultima_visita_dbbChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_ultima_visita_dbbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> loja_id
        {
            get
            {
                return _loja_id;
            }
            set
            {
                Onloja_idChanging(value);
                ReportPropertyChanging("loja_id");
                _loja_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("loja_id");
                Onloja_idChanged();
            }
        }
        private Nullable<global::System.Int32> _loja_id;
        partial void Onloja_idChanging(Nullable<global::System.Int32> value);
        partial void Onloja_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MinModel", "usuariosBlogComentariosUsers", "BlogComentarios")]
        public EntityCollection<BlogComentariosUsers> BlogComentariosXXX
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlogComentariosUsers>("MinModel.usuariosBlogComentariosUsers", "BlogComentarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlogComentariosUsers>("MinModel.usuariosBlogComentariosUsers", "BlogComentarios", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
